apiVersion: v1
kind: Service
metadata:
  name: { { include "autoappv11.webapi.fullname" . }-svc }
spec:
  type: ClusterIP
  selector:
    app: { { include "autoappv11.webapi.name" . } }
  ports:
    - port: 80
      targetPort: 80